services:
  - type: web
    name: hayacare-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TWOCHECKOUT_MERCHANT_CODE
        sync: false
      - key: TWOCHECKOUT_MODE
        value: PRODUCTION
